name       : haskell-th-reify-many
version    : 0.1.8
release    : 2
source     :
    - https://hackage.haskell.org/package/th-reify-many-0.1.8/th-reify-many-0.1.8.tar.gz : cecaae187df911de515d08929e1394d6d6f7ce129795be8189a6b10d3734fe43
license    : BSD-3-Clause
component  : programming.haskell
summary    : th-reify-many provides functions for recursively reifying top level declarations.
description: |
    th-reify-many provides functions for recursively reifying top level declarations.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-mtl
    - haskell-safe
    - haskell-th-expand-syns
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
