name       : haskell-th-reify-many
version    : 0.1.9
release    : 3
source     :
    - https://hackage.haskell.org/package/th-reify-many-0.1.9/th-reify-many-0.1.9.tar.gz : f889dd029d5ab191ace99fe595f363c60314d536e61c8c58f6167f1a9d29ae43
license    : BSD-3-Clause
component  : programming.haskell
summary    : th-reify-many provides functions for recursively reifying top level declarations.
description: |
    th-reify-many provides functions for recursively reifying top level declarations.
builddeps  :
    - haskell-cabal-install
    - haskell-safe-devel
    - haskell-th-expand-syns-devel
rundeps    :
    - devel:
        - haskell-safe-devel
        - haskell-th-expand-syns-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
