name       : haskell-th-reify-many
version    : 0.1.6
release    : 1
source     :
    - http://hackage.haskell.org/package/th-reify-many-0.1.6/th-reify-many-0.1.6.tar.gz : aea5d277af954ec41d8c129b9e0761a0e628b6e216d0243fb2600339bbfce6ac
license    : BSD-3-Clause
component  : programming.haskell
summary    : th-reify-many provides functions for recursively reifying top level declarations.
description: |
    th-reify-many provides functions for recursively reifying top level declarations.
builddeps  :
    - haskell-cabal-install
    - haskell-safe
    - haskell-th-expand-syns
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
